# Generated by Django 4.1.7 on 2023-03-03 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Credits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issuance_date", models.DateTimeField()),
                ("return_date", models.DateTimeField()),
                ("actual_return_date", models.DateTimeField(blank=True, null=True)),
                ("body", models.IntegerField()),
                ("percent", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                "ordering": ["issuance_date"],
            },
        ),
        migrations.CreateModel(
            name="Dictionary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login", models.CharField(max_length=255)),
                ("registration_date", models.DateTimeField()),
            ],
            options={
                "ordering": ["registration_date"],
            },
        ),
        migrations.CreateModel(
            name="Plans",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.DateTimeField()),
                ("sum", models.IntegerField()),
                (
                    "category_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.dictionary"
                    ),
                ),
            ],
            options={
                "ordering": ["period"],
            },
        ),
        migrations.CreateModel(
            name="Payments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sum", models.DecimalField(decimal_places=2, max_digits=5)),
                ("payment_date", models.DateTimeField()),
                (
                    "credit_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.credits"
                    ),
                ),
                (
                    "type_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.dictionary"
                    ),
                ),
            ],
            options={
                "ordering": ["payment_date"],
            },
        ),
        migrations.AddField(
            model_name="credits",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.user"
            ),
        ),
    ]
