# Generated by Django 4.1.7 on 2023-03-02 12:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dictionary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login", models.CharField(max_length=255)),
                (
                    "registration_date",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 3, 2, 12, 41, 4, 199778, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
            ],
            options={
                "ordering": ["registration_date"],
            },
        ),
        migrations.CreateModel(
            name="Credits",
            fields=[
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="app.user",
                    ),
                ),
                (
                    "issuance_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("return_date", models.DateTimeField()),
                ("actual_return_date", models.DateTimeField(blank=True, null=True)),
                ("body", models.IntegerField()),
                ("percent", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                "ordering": ["issuance_date"],
            },
        ),
        migrations.CreateModel(
            name="Plans",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.DateTimeField()),
                ("sum", models.IntegerField()),
                (
                    "category_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.dictionary"
                    ),
                ),
            ],
            options={
                "ordering": ["period"],
            },
        ),
        migrations.CreateModel(
            name="Payments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sum", models.DecimalField(decimal_places=2, max_digits=5)),
                ("payment_date", models.DateTimeField()),
                (
                    "type_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.dictionary"
                    ),
                ),
                (
                    "credit_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.credits"
                    ),
                ),
            ],
            options={
                "ordering": ["payment_date"],
            },
        ),
    ]
