# Generated by Django 4.1.7 on 2023-03-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="sum",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
